{{- if .Values.dotnetStatistik.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-dotnet-statistik
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: dotnet-statistik
spec:
  replicas: {{ .Values.dotnetStatistik.replicas }}
  selector:
    matchLabels:
      {{- include "sretodo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: dotnet-statistik
  template:
    metadata:
      labels:
        {{- include "sretodo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: dotnet-statistik
    spec:
      # Reference the global image pull secret
      imagePullSecrets:
        - name: {{ .Values.global.image.pullSecret }}
      # OpenShift compatible security context
      securityContext:
        fsGroup: 1011430000
      containers:
        - name: dotnet-statistik
          image: "{{ .Values.global.repositoryPrefix }}/{{ .Values.dotnetStatistik.imageName }}:{{ .Values.dotnetStatistik.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          env:
            - name: ASPNETCORE_URLS
              value: http://*:8080
            - name: TODO_SERVICE_HOST
              value: {{ include "sretodo.fullname" . }}-java-todo
            - name: TODO_SERVICE_PORT
              value: "{{ .Values.javaTodo.service.port | default 8080 }}"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://{{ .Release.Name }}-otel-collector:4317
          securityContext:
            runAsNonRoot: true
            runAsUser: 1011430000
            runAsGroup: 1011430000
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          # Health checks
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.dotnetStatistik.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dotnet-statistik
  labels:
    {{- include "sretodo.labels" . | nindent 4 }}
    app.kubernetes.io/component: dotnet-statistik
spec:
  type: {{ .Values.dotnetStatistik.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sretodo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dotnet-statistik
{{- end }}